services:
  discord:
    env_file: 
      - path: ".env.production"
        required: true
    restart: always
    volumes:
      - ./db/prodDatabase.sqlite:/usr/src/app/db/prodDatabase.sqlite
    build: .