const Sequelize = require('sequelize');

module.exports = function(sequelize, DataTypes){
    const Guild = sequelize.define('guild', {
        // this is actually the Discord-provided snowflake ID for the guild, not an ID generated by the database
        // there should only ever be one guild entry for a guild, so using this as the primary key forces data integrity
        id: {
            type: DataTypes.STRING,
            primaryKey: true
        }
    }, 
    {   underscored: true, 
        timestamps: true
    })

    return Guild;
}
